name: COMP3703
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.19=py311hd4eb7a1_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=heffb93a_0
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.9.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - krb5=1.21.3=h37d8d59_0
  - libcxx=21.1.8=h3d58e20_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libexpat=2.7.3=heffb93a_0
  - libffi=3.4.4=hecd8cb5_1
  - libsodium=1.0.20=hfdf4475_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h923df54_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h230baf5_0
  - packaging=26.0=pyhcf101f3_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.1=py311ha332486_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.13=hbff2529_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pyzmq=27.1.0=py311h0ab6910_0
  - readline=8.3=h49f2429_0
  - setuptools=78.1.1=py311hecd8cb5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hc8b0dd6_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h3a5a201_0
  - tornado=6.5.4=py311ha2bb86f_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=he532380_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zeromq=4.3.5=h6c33b1e_9
  - zlib=1.2.13=h4b97444_1
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - gast==0.7.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - joblib==1.5.3
      - keras==3.13.1
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - markdown==3.10.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - namex==0.1.0
      - numpy==1.26.4
      - opt-einsum==3.4.0
      - optree==0.18.0
      - pandas==3.0.0
      - pillow==12.1.0
      - protobuf==4.25.8
      - pyparsing==3.3.2
      - requests==2.32.5
      - rich==14.3.1
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - temporian==0.9.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==3.3.0
      - threadpoolctl==3.6.0
      - urllib3==2.6.3
      - werkzeug==3.1.5
      - wrapt==2.0.1
prefix: /opt/anaconda3/envs/test
